In [1]:
import os
os.chdir('U:\\GitHubClones\\SeniorDesign')
os.getcwd()
import Excel
import pandas as pd
from collections import OrderedDict
import re
from datetime import datetime

In [2]:
path = Excel.directory + "\\" + Excel.shelf + "\\" + Excel.dealName + "\\" + Excel.reportList[7]
print(path)

U:\AutoLoanTapes\Santander Drive Auto Receivables Trust\SDART 2017-1\2017\08 August\2017.09.15_Santander Drive Auto Receivables Trust 2017-1 Data Tape.csv

In [3]:
df = pd.read_csv(path, memory_map=True, low_memory=False)
total = len(df.index)

In [4]:
g= df.columns.to_series().groupby(df.dtypes).groups
g

{dtype('bool'): Index(['underwritingIndicator', 'coObligorIndicator',
        'reportingPeriodModificationIndicator', 'assetSubjectDemandIndicator',
        'repossessedIndicator'],
       dtype='object'),
 dtype('int64'): Index(['originalLoanTerm', 'interestCalculationTypeCode',
        'originalInterestRateTypeCode', 'gracePeriodNumber', 'paymentTypeCode',
        'vehicleNewUsedCode', 'vehicleModelYear', 'vehicleTypeCode',
        'vehicleValueSourceCode', 'obligorIncomeVerificationLevelCode',
        'obligorEmploymentVerificationCode', 'remainingTermToMaturityNumber',
        'servicingAdvanceMethodCode', 'currentDelinquencyStatus',
        'paymentExtendedNumber'],
       dtype='object'),
 dtype('float64'): Index(['originalLoanAmount', 'originalInterestRatePercentage',
        'vehicleValueAmount', 'paymentToIncomePercentage',
        'reportingPeriodBeginningLoanBalanceAmount',
        'nextReportingPeriodPaymentAmountDue',
        'reportingPeriodInterestRatePercentage', 'nextInterestRatePercentage',
        'servicingFeePercentage', 'otherAssessedUncollectedServicerFeeAmount',
        'scheduledInterestAmount', 'scheduledPrincipalAmount',
        'otherPrincipalAdjustmentAmount',
        'reportingPeriodActualEndBalanceAmount',
        'reportingPeriodScheduledPaymentAmount', 'totalActualAmountPaid',
        'actualInterestCollectedAmount', 'actualPrincipalCollectedAmount',
        'actualOtherCollectedAmount', 'chargedoffPrincipalAmount',
        'recoveredAmount'],
       dtype='object'),
 dtype('O'): Index(['assetTypeNumber', 'assetNumber', 'reportingPeriodBeginningDate',
        'reportingPeriodEndingDate', 'originatorName', 'originationDate',
        'loanMaturityDate', 'originalInterestOnlyTermNumber',
        'originalFirstPaymentDate', 'subvented', 'vehicleManufacturerName',
        'vehicleModelName', 'obligorCreditScoreType', 'obligorCreditScore',
        'obligorGeographicLocation', 'assetAddedIndicator',
        'servicingFlatFeeAmount', 'otherServicerFeeRetainedByServicer',
        'servicerAdvancedAmount', 'interestPaidThroughDate',
        'zeroBalanceEffectiveDate', 'zeroBalanceCode',
        'primaryLoanServicerName', 'mostRecentServicingTransferReceivedDate',
        'assetSubjectDemandStatusCode', 'repurchaseAmount',
        'DemandResolutionDate', 'repurchaserName',
        'repurchaseReplacementReasonCode', 'modificationTypeCode',
        'repossessedProceedsAmount'],
       dtype='object')}

In [90]:
print(df['obligorCreditScore'].describe())
print(df['subvented'].describe())
print(df['vehicleTypeCode'].describe())
print(df['vehicleValueSourceCode'].describe())
print(df['obligorIncomeVerificationLevelCode'].describe())
print(df['obligorEmploymentVerificationCode'].describe())
print(df['zeroBalanceCode'].describe())
#print(df['subvented'].describe())

count     61259
unique      483
top           -
freq       8677
Name: obligorCreditScore, dtype: object
count    61259.000000
mean         0.100334
std          0.040949
min          0.000779
25%          0.069135
50%          0.098897
75%          0.130413
max          0.388192
Name: paymentToIncomePercentage, dtype: float64
count    61259.000000
mean         0.166180
std          0.047626
min          0.000000
25%          0.136400
50%          0.170900
75%          0.196800
max          0.291700
Name: originalInterestRatePercentage, dtype: float64
count     61259
unique        5
top           0
freq      55877
Name: subvented, dtype: object
count    61259.000000
mean         1.630797
std          0.865396
min          1.000000
25%          1.000000
50%          1.000000
75%          3.000000
max          3.000000
Name: vehicleTypeCode, dtype: float64
count    61259.000000
mean        92.669926
std         21.862185
min          3.000000
25%         98.000000
50%         98.000000
75%         98.000000
max         98.000000
Name: vehicleValueSourceCode, dtype: float64
count    61259.000000
mean         2.112620
std          0.316131
min          2.000000
25%          2.000000
50%          2.000000
75%          2.000000
max          3.000000
Name: obligorIncomeVerificationLevelCode, dtype: float64
count    61259.000000
mean         2.010333
std          0.411411
min          1.000000
25%          2.000000
50%          2.000000
75%          2.000000
max          3.000000
Name: obligorEmploymentVerificationCode, dtype: float64

In [81]:
noScore = df[df.obligorCreditScore.isin(['-'])]
noScore['obligorCreditScore'].describe()

count     8677
unique       1
top          -
freq      8677
Name: obligorCreditScore, dtype: object

In [82]:
df['obligorCreditScore'] = pd.to_numeric(df['obligorCreditScore'], errors='coerce')
df['obligorCreditScore'].describe()

count    52582.000000
mean       602.994599
std         64.503203
min        385.000000
25%        562.000000
50%        600.000000
75%        637.000000
max        900.000000
Name: obligorCreditScore, dtype: float64

In [79]:
print(['paymentToIncomePercentage'].describe())
df['paymentToIncomePercentage'] = pd.to_numeric(df['paymentToIncomePercentage'], errors='coerce')

count    52582.000000
mean       602.994599
std         64.503203
min        385.000000
25%        562.000000
50%        600.000000
75%        637.000000
max        900.000000
Name: obligorCreditScore, dtype: float64
count    61259.000000
mean         0.100334
std          0.040949
min          0.000779
25%          0.069135
50%          0.098897
75%          0.130413
max          0.388192
Name: paymentToIncomePercentage, dtype: float64
count    61259.000000
mean         0.166180
std          0.047626
min          0.000000
25%          0.136400
50%          0.170900
75%          0.196800
max          0.291700
Name: originalInterestRatePercentage, dtype: float64

In [ ]:
df['originalInterestRatePercentage'] = pd.to_numeric(df['originalInterestRatePercentage'], errors='coerce')
print(df['originalInterestRatePercentage'].describe())

In [41]:
print(df['obligorCreditScore'].head())
#df['paymentToIncomePercentage'].head(50)

0         671
1    No Score
2         560
3         712
4         631
Name: obligorCreditScore, dtype: object

In [64]:
FicoBins = [-1, 440, 500, 560, 620, 680, 740, 800, 1000]
FicoGroup = ['[-1, 440)', '[440, 500)', '[500, 560)', '[560, 620)', '[620, 680)', '[680, 740)', '[740, 800)' , '[800, 1000)']
df['Fico Group'] = pd.cut(df['obligorCreditScore'], FicoBins, right=True, labels=FicoGroup)

df['Fico Group'] = df['Fico Group'].fillna(value='No Score')
df['Fico Group']

ValueError: fill value must be in categories

In [42]:

APRBins = [0, .02 ,.04, .06, .08, .1, .12, .14, .16, 1000]
#LTVBins = [-1, .7, .8, .9, 1, 1.1, 1.2, 1.3, 1.4, 1000]
PTIBins = [-1, .02, .04, .06, .08, .1, .12, .14, .16, 1000]

APRGroup = ['[0.0, 0.02)', '[0.02, 0.04)', '[0.04, 0.06)', '[0.06, 0.08)', '[0.08, 0.1)', '[0.1, 0.12)', '[0.12, 0.14)', '[0.14, 0.16)', '[0.16, 1000.0)']
PTIGroup = ['[-1.0, 0.02)', '[0.02, 0.04)', '[0.04, 0.06)', '[0.06, 0.08)', '[0.08, 0.1)', '[0.1, 0.12)', '[0.12, 0.14)', '[0.14, 0.16)', '[0.16, 1000.0)']

df['APR Group'] = pd.cut(df['originalInterestRatePercentage'], APRBins, labels=APRGroup)
df['PTI Group'] = pd.cut(df['paymentToIncomePercentage'], PTIBins, labels=PTIGroup)

TypeError: ufunc 'subtract' did not contain a loop with signature matching types dtype('S11') dtype('S11') dtype('S11')

In [32]:
f = OrderedDict([
        #('activeLoanFlag', ['sum']),
        ('reportingPeriodActualEndBalanceAmount', ['sum','mean']),
        #('pctBal', ['sum']),
        #('originalLoanTerm', {'Weighted Average' : wm}),
        #('remainingTermToMaturityNumber', {'Weighted Average' : wm}),
        #('APR' , {'Weighted Average' : wm}),
        #('LTV' , {'Weighted Average' : wm}),
        #('paymentToIncomePercentage', {'Weighted Average' : wm}),
        #('obligorCreditScore', {'Weighted Average' : wm})
    ])
#code for the risk layering stratification buckets 
groups = df[['reportingPeriodActualEndBalanceAmount', 'Fico Group']].groupby([df['Fico Group'], df['APR Group'],df['PTI Group']]).agg(f)
groups

                                          reportingPeriodActualEndBalanceAmount  \
                                                                            sum
Fico Group  APR Group      PTI Group
[-1, 440)   [0.1, 0.12)    [0.06, 0.08)                                37449.81
            [0.12, 0.14)   [0.04, 0.06)                                31338.90
                           [0.06, 0.08)                                20714.12
            [0.14, 0.16)   [0.04, 0.06)                                11383.39
                           [0.06, 0.08)                                 6885.12
                           [0.08, 0.1)                                 34382.58
                           [0.1, 0.12)                                 13478.88
            [0.16, 1000.0) [0.02, 0.04)                                26643.64
                           [0.04, 0.06)                               223473.64
                           [0.06, 0.08)                               374223.63
                           [0.08, 0.1)                                296475.58
                           [0.1, 0.12)                                126419.37
                           [0.12, 0.14)                               144244.76
                           [0.14, 0.16)                               124486.35
                           [0.16, 1000.0)                              60843.34
[440, 500)  [0.02, 0.04)   [0.06, 0.08)                                11614.77
            [0.04, 0.06)   [0.1, 0.12)                                 15360.18
                           [0.16, 1000.0)                              24502.60
            [0.06, 0.08)   [-1.0, 0.02)                                33736.50
                           [0.02, 0.04)                                30225.72
                           [0.04, 0.06)                                15426.52
                           [0.06, 0.08)                                43235.01
                           [0.1, 0.12)                                 17197.13
                           [0.12, 0.14)                                21275.99
                           [0.14, 0.16)                                17866.36
            [0.08, 0.1)    [-1.0, 0.02)                                26038.60
                           [0.02, 0.04)                                35193.29
                           [0.04, 0.06)                               100943.05
                           [0.06, 0.08)                                70692.75
                           [0.08, 0.1)                                101191.20
...                                                                         ...
[800, 1000) [0.08, 0.1)    [0.06, 0.08)                               749639.31
                           [0.08, 0.1)                                448780.86
                           [0.1, 0.12)                                217809.90
                           [0.12, 0.14)                               108633.07
                           [0.14, 0.16)                                20482.95
                           [0.16, 1000.0)                              63802.98
            [0.1, 0.12)    [-1.0, 0.02)                                14469.69
                           [0.02, 0.04)                               226407.21
                           [0.04, 0.06)                               469979.10
                           [0.06, 0.08)                               476812.82
                           [0.08, 0.1)                                104850.83
                           [0.1, 0.12)                                171217.61
                           [0.12, 0.14)                                33056.24
            [0.12, 0.14)   [-1.0, 0.02)                                 9031.36
                           [0.02, 0.04)                                78584.46
                           [0.04, 0.06)                               274006.99
                           [0.06, 0.08)                               158706.36
                           [0.08, 0.1)                                     0.00
                           [0.1, 0.12)                                 65935.49
                           [0.12, 0.14)                                78974.15
                           [0.14, 0.16)                                30720.99
            [0.14, 0.16)   [-1.0, 0.02)                                15322.46
                           [0.02, 0.04)                                13696.18
                           [0.04, 0.06)                               108310.34
                           [0.06, 0.08)                               218223.56
                           [0.08, 0.1)                                 72939.20
                           [0.1, 0.12)                                 60627.53
                           [0.12, 0.14)                                45603.36
            [0.16, 1000.0) [0.04, 0.06)                                51712.30
                           [0.08, 0.1)                                 22873.50


                                                   mean
Fico Group  APR Group      PTI Group
[-1, 440)   [0.1, 0.12)    [0.06, 0.08)    18724.905000
            [0.12, 0.14)   [0.04, 0.06)    10446.300000
                           [0.06, 0.08)    20714.120000
            [0.14, 0.16)   [0.04, 0.06)    11383.390000
                           [0.06, 0.08)     6885.120000
                           [0.08, 0.1)     11460.860000
                           [0.1, 0.12)     13478.880000
            [0.16, 1000.0) [0.02, 0.04)    13321.820000
                           [0.04, 0.06)    11173.682000
                           [0.06, 0.08)    12474.121000
                           [0.08, 0.1)     12890.242609
                           [0.1, 0.12)     11492.670000
                           [0.12, 0.14)    10303.197143
                           [0.14, 0.16)    11316.940909
                           [0.16, 1000.0)  12168.668000
[440, 500)  [0.02, 0.04)   [0.06, 0.08)    11614.770000
            [0.04, 0.06)   [0.1, 0.12)     15360.180000
                           [0.16, 1000.0)  24502.600000
            [0.06, 0.08)   [-1.0, 0.02)    16868.250000
                           [0.02, 0.04)    10075.240000
                           [0.04, 0.06)    15426.520000
                           [0.06, 0.08)    21617.505000
                           [0.1, 0.12)     17197.130000
                           [0.12, 0.14)    21275.990000
                           [0.14, 0.16)     8933.180000
            [0.08, 0.1)    [-1.0, 0.02)    26038.600000
                           [0.02, 0.04)     8798.322500
                           [0.04, 0.06)    14420.435714
                           [0.06, 0.08)    17673.187500
                           [0.08, 0.1)     33730.400000
...                                                 ...
[800, 1000) [0.08, 0.1)    [0.06, 0.08)    23426.228438
                           [0.08, 0.1)     24932.270000
                           [0.1, 0.12)     36301.650000
                           [0.12, 0.14)    27158.267500
                           [0.14, 0.16)    20482.950000
                           [0.16, 1000.0)  31901.490000
            [0.1, 0.12)    [-1.0, 0.02)     7234.845000
                           [0.02, 0.04)    15093.814000
                           [0.04, 0.06)    17406.633333
                           [0.06, 0.08)    20730.992174
                           [0.08, 0.1)     17475.138333
                           [0.1, 0.12)     24459.658571
                           [0.12, 0.14)    16528.120000
            [0.12, 0.14)   [-1.0, 0.02)     9031.360000
                           [0.02, 0.04)    13097.410000
                           [0.04, 0.06)    16118.058235
                           [0.06, 0.08)    15870.636000
                           [0.08, 0.1)         0.000000
                           [0.1, 0.12)     21978.496667
                           [0.12, 0.14)    26324.716667
                           [0.14, 0.16)    30720.990000
            [0.14, 0.16)   [-1.0, 0.02)    15322.460000
                           [0.02, 0.04)    13696.180000
                           [0.04, 0.06)    15472.905714
                           [0.06, 0.08)    19838.505455
                           [0.08, 0.1)     18234.800000
                           [0.1, 0.12)     15156.882500
                           [0.12, 0.14)    22801.680000
            [0.16, 1000.0) [0.04, 0.06)    25856.150000
                           [0.08, 0.1)     22873.500000

[483 rows x 2 columns]

In [14]:
print(df.size)
print(df['obligorCreditScore'].describe())
df = df[~df.obligorCreditScore.isin(['-'])]
df['obligorCreditScore'] = pd.to_numeric(df['obligorCreditScore'], errors='coerce')
print(df['obligorCreditScore'].describe())
61259-52582

3785904
count    52582.000000
mean       602.994599
std         64.503203
min        385.000000
25%        562.000000
50%        600.000000
75%        637.000000
max        900.000000
Name: obligorCreditScore, dtype: float64
count    52582.000000
mean       602.994599
std         64.503203
min        385.000000
25%        562.000000
50%        600.000000
75%        637.000000
max        900.000000
Name: obligorCreditScore, dtype: float64

8677

In [ ]:
stratDict = {
    'FICO' : (-1, 440, 500, 560, 620, 680, 740, 800, 1000),
    'LTV' : (-1, .7, .8, .9, 1, 1.1, 1.2, 1.3, 1.4, 1000),
    'PTI' : (-1, .02, .04, .06, .08, .1, .12, .14, .16, 1000),
    'APR' : (0, .02 ,.04, .06, .08, .1, .12, .14, .16, 1000)
}